### SIGN IN AS A NEW USER
POST localhost:3000/auth/signup
content-type: application/json

{
  "email": "chamara11aqqq@gmail.com",
  "password": "password"
}

### SIGN UP AS A EXSISTING USER
POST localhost:3000/auth/signin
content-type: application/json

{
  "email": "chamara1aqq@gmail.com",
  "password": "password"
}

### SIGN OUT
POST localhost:3000/auth/signout

### FIND A USER
GET localhost:3000/auth/9

### FIND ALL USER
GET localhost:3000/auth?email=abc@email.com

### DELETE A USER
DELETE localhost:3000/auth/8

### UPDATE A USER
PATCH localhost:3000/auth/9
content-type: application/json

{
  "email": "chamara@gmail.com",
  "password": "111111"
}

### SIGNIN A USER
POST localhost:3000/auth/signin
content-type: application/json

{
  "email": "chamara1aqq@gmail.com",
  "password": "password"
}

### GET CURRENT USER
GET localhost:3000/auth/whoami